version: '3'
services:
  web:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      # - ./node_modules/eq-author-graphql-schema:/app/node_modules/eq-author-graphql-schema
    ports:
      - 4000:4000
      - 5858:5858 # open port for debugging
    environment:
      - DB_CONNECTION_URI=postgres://postgres:mysecretpassword@db:5432/postgres
      - GRAPHIQL_ENABLED=true
      - GRAPHIQL_ENDPOINT=/graphiql
      - GRAPHIQL_PRETTY=true
      - NODE_ENV=development
    entrypoint:
      - yarn
      - start:dev
  db:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
