version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    ports:
      - 4000:4000
  db:
    image: postgres
    environment:
      - POSTGRES_USER:"postgres"
      - POSTGRES_PASSWORD:"mysecretpassword"
      - POSTGRES_DB:"postgres"
    ports:
      - 5432:5432
