version: '3'
services:
  web:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      - EXPRESS_PORT=4000
      - GRAPHIQL_ENABLED=true
      - GRAPHIQL_ENDPOINT=/graphiql
      - GRAPHIQL_PRETTY=true
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOSTNAME=db
      - DB_DIALECT=postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
